version: '3.9'

services:
  back:
    container_name: back
    build:
      context: .
      args:
        - POETRY_DEV=true
    env_file:
      - env-local
    volumes:
      - ./app:/app
      - ~/.aws/jpg_credentials:/root/.aws/credentials:ro
      - ~/.aws/jpg_config:/root/.aws/config:ro
    ports:
      - 8777:80
    depends_on:
      - db
    command: >
      bash -c "python manage.py wait_for_db &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:80"
    networks:
      - jpg-network

  db:
    container_name: db
    image: postgres:13.7
    env_file:
      - env-local
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - jpg-network

volumes:
  db-data:

networks:
  jpg-network:
    external: true