# Generated by Django 4.2 on 2023-04-28 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversationmodel",
            name="conversation_file",
            field=models.FileField(null=True, upload_to=""),
        ),
    ]
