# Generated by Django 4.2 on 2023-04-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversation", "0002_patientmodel_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversationmodel",
            name="conversation",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
