# Generated by Django 4.2 on 2023-04-29 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("conversation", "0004_remove_conversationmodel_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnswerModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="conversation.patientmodel",
                    ),
                ),
                (
                    "relevant_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="conversation.relevantpointmodel",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Answer Versions",
                "ordering": ("updated_at",),
            },
        ),
        migrations.AlterField(
            model_name="conversationmodel",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations",
                to="conversation.patientmodel",
            ),
        ),
        migrations.DeleteModel(
            name="AnswerVersionModel",
        ),
    ]
