# Generated by Django 4.2 on 2023-04-30 00:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversation", "0005_answermodel_alter_conversationmodel_patient_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversationmodel",
            name="duration",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
