# Generated by Django 4.2 on 2023-04-30 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("conversation", "0006_conversationmodel_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="answermodel",
            name="conversation",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="conversation.conversationmodel",
            ),
            preserve_default=False,
        ),
    ]
