# Generated by Django 4.2 on 2023-04-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversation", "0007_answermodel_conversation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientmodel",
            name="email",
            field=models.EmailField(max_length=255),
        ),
    ]
