# Generated by Django 4.2 on 2023-04-30 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("conversation", "0008_alter_patientmodel_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="EphemeralAnswerModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ephemeral_answers",
                        to="conversation.conversationmodel",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Ephemeral Answers",
                "ordering": ("updated_at",),
            },
        ),
    ]
