# Generated by Django 4.2 on 2023-05-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversation", "0010_relevantpointmodel_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answermodel",
            options={"ordering": ("updated_at",), "verbose_name_plural": "Answers"},
        ),
        migrations.RemoveField(
            model_name="answermodel",
            name="conversation",
        ),
        migrations.AddField(
            model_name="conversationmodel",
            name="draft",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="conversationmodel",
            name="status",
            field=models.CharField(
                choices=[("DRAFT", "draft"), ("CONSOLIDATED", "consolidated")],
                default="draft",
                max_length=20,
            ),
        ),
    ]
