# Generated by Django 4.2 on 2023-05-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversation", "0012_alter_answermodel_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="answermodel",
            name="resolved",
            field=models.BooleanField(default=False),
        ),
    ]
