# Generated by Django 4.2 on 2023-05-04 22:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversation", "0013_answermodel_resolved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answermodel",
            name="text",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="relevantpointmodel",
            name="category",
            field=models.CharField(
                choices=[
                    ("PERSONAL", "Personal"),
                    ("ECONOMICO", "Económico"),
                    ("LABORAL", "Laboral"),
                    ("FAMILIAR", "Familiar"),
                    ("AMBIENTAL_VIVIENDA", "Ambiental y de Vivienda"),
                    ("SALUD", "de la Salud"),
                    ("SOCIAL", "Social"),
                ],
                default="Personal",
                max_length=20,
            ),
        ),
    ]
