# Generated by Django 4.2 on 2023-05-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversation", "0014_alter_answermodel_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answermodel",
            name="created_at",
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name="answermodel",
            name="updated_at",
            field=models.DateTimeField(),
        ),
    ]
